apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "age.fullname" . }}-pvc
  labels:
    {{- include "age.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
